# Generated by Django 4.2.4 on 2023-08-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_track_audio_file_alter_album_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.author'),
        ),
    ]
