# Generated by Django 4.2.4 on 2023-08-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_track_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='name',
            new_name='title',
        ),
    ]
